import type { IColorSchemeStruct } from '../interface';
export type BuiltinColorPalette = IColorSchemeStruct['palette'] & {
    backgroundColor: string;
    borderColor: string;
    shadowColor: string;
    hoverBackgroundColor: string;
    sliderRailColor: string;
    sliderHandleColor: string;
    sliderTrackColor: string;
    popupBackgroundColor: string;
    primaryFontColor: string;
    secondaryFontColor: string;
    tertiaryFontColor: string;
    axisLabelFontColor: string;
    disableFontColor: string;
    axisMarkerFontColor: string;
    axisGridColor: string;
    axisDomainColor: string;
    dataZoomHandleStrokeColor: string;
    dataZoomChartColor: string;
    playerControllerColor: string;
    scrollBarSliderColor: string;
    axisMarkerBackgroundColor: string;
    markLabelBackgroundColor: string;
    markLineStrokeColor: string;
};
