import type { IColorSchemeStruct } from '../interface';
export type BuiltinColorPalette = IColorSchemeStruct['palette'] & {
    backgroundColor: string;
    borderColor: string;
    shadowColor: string;
    primaryFontColor: string;
    secondaryFontColor: string;
    axisFontColor: string;
    disableFontColor: string;
    labelReverseFontColor: string;
    axisGridColor: string;
    axisDomainColor: string;
    dataZoomHandlerStrokeColor: string;
    dataZoomHandlerFillColor: string;
    dataZoomBackgroundColor: string;
    dataZoomChartColor: string;
    dataZoomSelectedColor: string;
    scrollBarSliderColor: string;
    tooltipBackgroundColor: string;
    markLabelBackgroundColor: string;
};
