import { PREFIX } from './base';

export const ARC_TRANSFORM_VALUE = `${PREFIX}_ARC_TRANSFORM_VALUE`;
export const ARC_RATIO = `${PREFIX}_ARC_RATIO`;
export const ARC_START_ANGLE = `${PREFIX}_ARC_START_ANGLE`;
export const ARC_END_ANGLE = `${PREFIX}_ARC_END_ANGLE`;
export const ARC_K = `${PREFIX}_ARC_K`;
export const ARC_LABEL_HOVER_AX = `${PREFIX}_ARC_LABEL_HOVER_AX`;
export const ARC_LABEL_HOVER_AY = `${PREFIX}_ARC_LABEL_HOVER_AY`;
export const ARC_LABEL_POINT_AX = `${PREFIX}_ARC_LABEL_POINT_AX`;
export const ARC_LABEL_POINT_AY = `${PREFIX}_ARC_LABEL_POINT_AY`;
export const ARC_LABEL_POINT_BX = `${PREFIX}_ARC_LABEL_POINT_BX`;
export const ARC_LABEL_POINT_BY = `${PREFIX}_ARC_LABEL_POINT_BY`;
export const ARC_LABEL_POINT_CX = `${PREFIX}_ARC_LABEL_POINT_CX`;
export const ARC_LABEL_POINT_CY = `${PREFIX}_ARC_LABEL_POINT_CY`;
export const ARC_LABEL_SELECTED_AX = `${PREFIX}_ARC_LABEL_SELECTED_AX`;
export const ARC_LABEL_SELECTED_AY = `${PREFIX}_ARC_LABEL_SELECTED_AY`;
export const ARC_MIDDLE_ANGLE = `${PREFIX}_ARC_MIDDLE_ANGLE`;
export const ARC_QUADRANT = `${PREFIX}_ARC_QUADRANT`;
export const ARC_RADIAN = `${PREFIX}_ARC_RADIAN`;

export const POLAR_START_RADIAN = -Math.PI / 2;
export const POLAR_END_RADIAN = (3 * Math.PI) / 2;

export const POLAR_START_ANGLE = -90;
export const POLAR_END_ANGLE = 270;

export const POLAR_DEFAULT_RADIUS = 0.6;
