import type { SVGParsedElement, SVGParserResult } from '@visactor/vdataset';
import type { PanEventParam, ZoomEventParam } from '../../core';
import { GeoSeries } from '../geo/geo';
import type { ISeriesSeriesInfo, SeriesMarkMap } from '../interface';
import { SeriesTypeEnum } from '../interface';
import type { IPictogramSeriesSpec } from './interface';
import type { GroupMark } from '../../mark';
import { PictogramSeriesSpecTransformer } from './pictogram-transformer';
import type { IMatrix } from '@visactor/vutils';
import type { Datum } from '../../typings';
import type { GraphicEventType, IGroup } from '@visactor/vrender-core';
import type { IHoverSpec, ISelectSpec } from '../../interaction/interface/spec';
import { STATE_VALUE_ENUM } from '../../compile/mark';
import type { IMark } from '../../mark/interface';
import type { IPoint } from '../../typings/coordinate';
import { TRIGGER_TYPE_ENUM } from '../../interaction/triggers/enum';
export interface SVGParsedElementExtend extends SVGParsedElement {
    _finalAttributes: Record<string, any>;
    _uniqueId: string;
}
export declare class PictogramSeries<T extends IPictogramSeriesSpec = IPictogramSeriesSpec> extends GeoSeries<T> {
    static readonly type: string;
    type: SeriesTypeEnum;
    static readonly mark: SeriesMarkMap;
    static readonly transformerConstructor: typeof PictogramSeriesSpecTransformer;
    svg: string;
    protected _pictogramMark: GroupMark;
    protected _parsedSvgResult: SVGParserResult;
    private _labelMark;
    private _idToMark;
    setAttrFromSpec(): void;
    getDatumCenter(datum: SVGParsedElementExtend): [number, number];
    getDatumName(datum: SVGParsedElementExtend): string;
    getMarksWithoutRoot(): IMark[];
    protected _buildMarkAttributeContext(): void;
    protected _defaultHoverConfig(finalHoverSpec: IHoverSpec): {
        type: TRIGGER_TYPE_ENUM;
        trigger: GraphicEventType;
        triggerOff: GraphicEventType;
        blurState: STATE_VALUE_ENUM;
        highlightState: STATE_VALUE_ENUM;
    };
    protected _defaultSelectConfig(finalSelectSpec: ISelectSpec): {
        type: TRIGGER_TYPE_ENUM;
        trigger: GraphicEventType;
        triggerOff: GraphicEventType;
        reverseState: STATE_VALUE_ENUM;
        state: STATE_VALUE_ENUM;
        isMultiple: boolean;
    };
    initMark(): void;
    private _initLabelMark;
    initLabelMarkStyle(): void;
    initMarkStyle(): void;
    protected _validElement(element: SVGParsedElement): string;
    protected initTooltip(): void;
    dataToPosition(datum: Datum, global?: boolean): IPoint;
    coordToPosition(point: IPoint): IPoint | undefined;
    getRootMatrix(): IMatrix;
    getPictogramRootGraphic(): IGroup;
    initData(): void;
    mapViewDataUpdate(): void;
    onLayoutEnd(): void;
    updateSVGSize(): void;
    protected initEvent(): void;
    handleZoom(e: ZoomEventParam): void;
    handlePan(e: PanEventParam): void;
    getMarkData(datum: Datum): any;
    getMeasureField(): string[];
    getDimensionField(): string[];
    protected _getSeriesInfo(field: string, keys: string[]): ISeriesSeriesInfo[];
    release(): void;
}
export declare const registerPictogramSeries: () => void;
