export type SeriesType = keyof typeof SeriesTypeEnum | string;

export enum SeriesTypeEnum {
  area = 'area',
  line = 'line',
  bar = 'bar',
  bar3d = 'bar3d',
  rangeColumn = 'rangeColumn',
  rangeColumn3d = 'rangeColumn3d',
  rangeArea = 'rangeArea',
  dot = 'dot',
  geo = 'geo',
  link = 'link',
  map = 'map',
  pie = 'pie',
  pie3d = 'pie3d',
  radar = 'radar',
  rose = 'rose',
  scatter = 'scatter',
  circularProgress = 'circularProgress',
  wordCloud = 'wordCloud',
  wordCloud3d = 'wordCloud3d',
  funnel = 'funnel',
  funnel3d = 'funnel3d',
  linearProgress = 'linearProgress',
  boxPlot = 'boxPlot',
  sankey = 'sankey',
  gaugePointer = 'gaugePointer',
  gauge = 'gauge',
  treemap = 'treemap',
  sunburst = 'sunburst',
  circlePacking = 'circlePacking',
  waterfall = 'waterfall',
  heatmap = 'heatmap'
}
