import type { IComponentOption } from '../interface';
import { ComponentTypeEnum } from '../interface/type';
import type { IModelLayoutOption, IModelRenderOption } from '../../model/interface';
import type { IRegion } from '../../region/interface';
import { BaseComponent } from '../base/base-component';
import type { BaseEventParams, EventCallback, EventQuery, EventType } from '../../event/interface';
import type { ITooltipHandler, IToolTipLineActual, TooltipActiveType } from '../../typings/tooltip';
import type { Datum, ILayoutType, IShowTooltipOption } from '../../typings';
import type { ITooltip, ITooltipActiveTypeAsKeys, ITooltipSpec, ITooltipTheme, TooltipHandlerParams, TotalMouseEventData } from './interface';
import { TooltipResult } from './interface/common';
import { DimensionTooltipProcessor } from './processor/dimension-tooltip';
import { MarkTooltipProcessor } from './processor/mark-tooltip';
import type { IGraphic } from '@visactor/vrender-core';
export type TooltipActualTitleContent = {
    title?: IToolTipLineActual;
    content?: IToolTipLineActual[];
};
export declare class Tooltip extends BaseComponent<any> implements ITooltip {
    protected layoutZIndex: number;
    static type: ComponentTypeEnum;
    type: ComponentTypeEnum;
    name: string;
    layoutType: ILayoutType;
    protected _spec: ITooltipSpec;
    static createComponent(spec: any, options: IComponentOption): Tooltip | Tooltip[];
    tooltipHandler?: ITooltipHandler;
    private _alwaysShow;
    private _cacheInfo;
    private _eventList;
    protected _theme: ITooltipTheme;
    protected _processor: ITooltipActiveTypeAsKeys<MarkTooltipProcessor, DimensionTooltipProcessor>;
    protected _isTooltipShown: boolean;
    isTooltipShown(): boolean;
    changeRegions(regions: IRegion[]): void;
    getVRenderComponents(): IGraphic[];
    protected _registerEvent(): void;
    protected _releaseEvent(): void;
    onLayout(ctx: IModelLayoutOption): void;
    onLayoutEnd(ctx: IModelLayoutOption): void;
    onRender(ctx: IModelRenderOption): void;
    created(): void;
    release(): void;
    beforeRelease(): void;
    protected _initHandler(): void;
    protected _initProcessor(): void;
    protected _initEvent(): void;
    protected _mountEvent: (eType: EventType, query: EventQuery, callback: EventCallback<any>) => void;
    protected _getMouseOutHandler: (needPointerDetection?: boolean) => (params: BaseEventParams) => void;
    protected _handleChartMouseOut: (params: BaseEventParams) => void;
    protected _handleMouseMove: (params: BaseEventParams) => void;
    protected _showTooltipByMouseEvent: (activeType: TooltipActiveType, mouseEventData: TotalMouseEventData, params: BaseEventParams, useCache?: boolean) => boolean;
    protected _getMouseEventData: (params: BaseEventParams) => TotalMouseEventData;
    protected _hideTooltipByHandler: (params: TooltipHandlerParams) => TooltipResult;
    protected _initTheme(theme?: any): void;
    protected _shouldMergeThemeToSpec(): boolean;
    reInit(theme?: any): void;
    setAttrFromSpec(): void;
    showTooltip(datum: Datum, options: IShowTooltipOption): false | "none" | TooltipActiveType;
    hideTooltip(): boolean;
    private _isSameAsCacheInfo;
    private _isPointerInChart;
    private _isPointerOnTooltip;
    getVisible(): boolean;
}
export declare const registerTooltip: () => void;
