export declare const FUNNEL_TRANSFORM_RATIO: string;
export declare const FUNNEL_REACH_RATIO: string;
export declare const FUNNEL_HEIGHT_RATIO: string;
export declare const FUNNEL_VALUE_RATIO: string;
export declare const FUNNEL_LAST_VALUE_RATIO: string;
export declare const FUNNEL_NEXT_VALUE_RATIO: string;
export declare const FUNNEL_LAST_VALUE: string;
export declare const FUNNEL_CURRENT_VALUE: string;
export declare const FUNNEL_NEXT_VALUE: string;
export declare const FUNNEL_TRANSFORM_LEVEL: string;
export declare const FUNNEL_LABEL_LINE_LENGTH = 20;
export declare const FUNNEL_LABEL_SPACE_WIDTH = 5;
export declare const FUNNEL_MAX_SIZE = "80%";
export declare const FUNNEL_MIN_SIZE = 0;
