import { type IBoundsLike } from '@visactor/vutils';
import { ComponentTypeEnum, type IComponentOption } from '../../interface';
import { DataFilterBaseComponent } from '../data-filter-base-component';
import { DataZoom as DataZoomComponent } from '@visactor/vrender-components';
import type { IRectGraphicAttribute, ISymbolGraphicAttribute, IGraphic } from '@visactor/vrender-core';
import type { Datum, ILayoutRect, ILayoutType } from '../../../typings';
import { type ILinearScale, type IBaseScale } from '@visactor/vscale';
import type { IDataZoomSpec } from './interface';
import { DataZoomSpecTransformer } from './data-zoom-transformer';
export declare class DataZoom<T extends IDataZoomSpec = IDataZoomSpec> extends DataFilterBaseComponent<T> {
    static type: ComponentTypeEnum;
    static readonly transformerConstructor: any;
    type: ComponentTypeEnum;
    name: string;
    readonly transformerConstructor: typeof DataZoomSpecTransformer;
    static readonly builtInTheme: {
        dataZoom: import("./interface").IDataZoomTheme;
    };
    static specKey: string;
    specKey: string;
    layoutZIndex: number;
    layoutLevel: number;
    layoutType: ILayoutType;
    protected _component: DataZoomComponent;
    protected _valueScale: ILinearScale;
    protected _backgroundSize: number;
    protected _middleHandlerSize: number;
    protected _startHandlerSize: number;
    protected _endHandlerSize: number;
    protected _isReverseCache: boolean;
    protected _cacheRect?: ILayoutRect;
    protected _previewStateScale: IBaseScale;
    constructor(spec: T, options: IComponentOption);
    protected _handleChange(start: number, end: number, updateComponent?: boolean, tag?: string): void;
    protected _handleDataCollectionChange(): void;
    created(): void;
    updateLayoutAttribute(): void;
    protected _beforeLayoutEnd(): void;
    clear(): void;
    getBoundsInRect(rect: ILayoutRect): IBoundsLike;
    setAttrFromSpec(): void;
    protected _initValueScale(): void;
    protected _updateScaleRange(): void;
    protected _updateStateScaleRange(): void;
    protected _updateValueScaleRange(): void;
    protected _computeDomainOfValueScale(): unknown[];
    protected _isScaleValid(scale: IBaseScale | ILinearScale): boolean;
    protected _getXScale(): IBaseScale | ILinearScale;
    protected _getYScale(): IBaseScale | ILinearScale;
    protected _dataToPositionX: (datum: Datum) => number;
    protected _dataToPositionX2: (datum: Datum) => number;
    protected _dataToPositionY: (datum: Datum) => number;
    protected _dataToPositionY2: (datum: Datum) => number;
    protected _computeMiddleHandlerSize(): number;
    protected _computeWidth(): number;
    protected _computeHeight(): number;
    private _getAttrs;
    private _getLayoutAttrs;
    protected _createOrUpdateComponent(changeData?: boolean): void;
    protected _getComponentAttrs(isNeedPreview: boolean): {
        backgroundStyle: IRectGraphicAttribute;
        startHandlerStyle: ISymbolGraphicAttribute;
        middleHandlerStyle: {
            visible: boolean;
            icon: ISymbolGraphicAttribute;
            background: any;
        } | {
            visible: boolean;
            icon?: undefined;
            background?: undefined;
        };
        endHandlerStyle: ISymbolGraphicAttribute;
        startTextStyle: unknown;
        endTextStyle: unknown;
        selectedBackgroundStyle: IRectGraphicAttribute;
        dragMaskStyle: IRectGraphicAttribute;
        backgroundChartStyle: {
            line: any;
            area: any;
        };
        selectedBackgroundChartStyle: {
            line: any;
            area: any;
        };
        disableTriggerEvent: boolean;
    };
    protected _getHandlerTextFormatMethod(spec: IDataZoomSpec['startText']): (text: any) => any;
    protected _getNeedClearVRenderComponents(): IGraphic[];
    onDataUpdate(): void;
    protected _getPreviewStateScale(): IBaseScale;
}
export declare const registerDataZoom: () => void;
