name: Bug Server CI

# 这里业务方根据需求设置
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main', 'develop', 'dev/**']

jobs:
  build:
    runs-on: macos-13

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './common/config/rush/pnpm-lock.yaml'

      - name: Print All Github Environment Variables
        run: env

      - name: Install rush
        run: node common/scripts/install-run-rush.js install --bypass-policy

      - name: Build vutils-extension
        working-directory: ./packages/vutils-extension
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: node ../../common/scripts/install-run-rushx.js build:es

      - name: Build vchart
        working-directory: ./packages/vchart
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: node ../../common/scripts/install-run-rushx.js build:es

      - name: Build vchart-extension
        working-directory: ./packages/vchart-extension
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: node ../../common/scripts/install-run-rushx.js build:es

      - name: Build bugserver-trigger
        working-directory: ./tools/bugserver-trigger
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: node ../../common/scripts/install-run-rushx.js build

      - name: Run CI
        working-directory: ./tools/bugserver-trigger
        env:
          BUG_SERVER_TOKEN: ${{ secrets.BUG_SERVER_TOKEN }}
        run: node ../../common/scripts/install-run-rushx.js ci
